name    'desalvo-rpcbind'
version '0.1.0'
source 'https://github.com/desalvo/puppet-rpcbind'
author 'desalvo'
license 'Apache License, Version 2.0'
summary 'Puppet module for rpcbind/portmap setup'
description 'A puppet module for setting up rpcbind/portmap services'
project_page 'https://github.com/desalvo/puppet-rpcbind'
